name: CI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-ip-cores:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Icarus Verilog
      run: |
        sudo apt-get update
        sudo apt-get install -y iverilog
    
    - name: Test AXI4-Lite GPIO IP Core
      run: |
        cd ip_cores/axi_lite_gpio
        make test
        make clean
    
    - name: Test AXI4-Lite UART IP Core  
      run: |
        cd ip_cores/axi_lite_uart
        make test
        make clean
    
    - name: Run GPIO Examples
      run: |
        cd ip_cores/axi_lite_gpio
        make example
        make clean
    
    - name: Run UART Examples (if available)
      run: |
        cd ip_cores/axi_lite_uart
        if [ -d "examples" ]; then
          make example
        else
          echo "No examples directory found for UART - skipping"
        fi
        make clean